# Generated by Django 4.2 on 2024-09-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='main_page.product'),
        ),
    ]
