# Generated by Django 4.2 on 2024-09-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='products',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='products',
            field=models.ManyToManyField(to='main_page.product'),
        ),
    ]
