# Generated by Django 4.2 on 2024-09-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_remove_cartitem_products_cartitem_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quntity',
        ),
    ]
